### ISSUE TITLE
Konomi PC duct section too thin.

### ISSUE THREAD

**Issue by Dr-Info** [bigtreetech/KNOMI#1]
Part has a section with a lack of material for printing with voron print specs, .2mm layer height. I checked the STL and even exported the STL from the CAD, both have the same issue.

![konomi issue sliced file](https://user-images.githubusercontent.com/79484322/235947445-e78a5369-e8ce-4a16-a585-017637701479.JPG)

**Comment by bigtreetech** [comment]
Fixed in https://github.com/bigtreetech/KNOMI/commit/eafe51ef290f9e47f16155080b72e3c8a89418d7
