### ISSUE TITLE
Failed to connect to ESP32: No serial data received

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/KNOMI#11]
It's impossible for me to flash Knomi. I have tested on MacOS and Windows, same issue.

<img width="1413" alt="Capture d’écran 2023-05-31 à 03 49 04" src="https://github.com/bigtreetech/KNOMI/assets/12702322/09447403-1105-4d51-aeb9-738ea4e2f642">

Serial Console detect Knomi but impossible to flash it :

<img width="1465" alt="Capture d’écran 2023-05-31 à 03 50 24" src="https://github.com/bigtreetech/KNOMI/assets/12702322/59cd873e-a1bf-4dec-9b03-2764bac746a7">

**Comment by oMTEo** [comment]
To upload Firmware to Knomi follow these steps :
-Remove Knomi from USB-Port.
-Push Upload in VSCode and wait till "Connecting....."
-Hold down the Boot-Button on Knomi, plug it back to the USB-Port and release Boot-Button.
