### ISSUE TITLE
Newest STL does not include the mounting plate

### ISSUE THREAD

**Issue by Cyondil** [bigtreetech/KNOMI#3]
The file only contains the Stealthburner cover, no mounting plate.

**Comment by neriux912** [comment]
It is in step file, but not in stl

**Comment by neriux912** [comment]
> The file only contains the Stealthburner cover, no mounting plate.

https://github.com/neriux912/KNOMI/blob/master/Customized%20Printed%20Parts/Mounting%20Plate.stl

**Comment by Cyondil** [comment]
Looks like it was added after I looked.
