### ISSUE TITLE
KNOMI GIF

### ISSUE THREAD

**Issue by CBoismenu** [bigtreetech/KNOMI#31]
Not a problem with KNOMI itself but a problem with the GIF file subblied by BigTreeTech.

The GIF for leveling in the ZIP file is not the same as the one used in the original firmware.

The one in the firmware is a hotend going up an down, the onr in the ZIP file is like the circles that would be created by throwing a rock in water.

I've searched and could not find the original leveling GIF used by BTT.

Would it be possible to get a copy of the original leveling GIF.

Thanks,

**Comment by lvlacleod** [comment]
![levelling](https://github.com/bigtreetech/KNOMI/assets/51907297/1cdd3b84-5734-4932-bc80-4d52ac09413a)

**Comment by CBoismenu** [comment]
Thank's that was quick.
