### ISSUE TITLE
E3d Volcano?

### ISSUE THREAD

**Issue by el-quique** [bigtreetech/KNOMI#4]
Hello. Any chance for E3d Volcano? Thank you so much

**Comment by hdragoon** [comment]
What does this have to do with e3d volcano hotend?

**Comment by el-quique** [comment]
Hello. Thanks for answering. It is for use in an Artillery X1 printer. This printer uses the E3d Volcano, as its X axis uses a 2060 profile it needs the E3d volcano. There are some Stealthburner mods on thingiverse, but they have some bugs.

**Comment by el-quique** [comment]
New change in the assembly design that I am designing, would give me the possibility of using a standard E3d v6. Maybe use a high flow nozzle. Thank you so much
