### ISSUE TITLE
Accelation display for Z shows almost alway full bar

### ISSUE THREAD

**Issue by lukicsl** [bigtreetech/KNOMI#42]
I have installed Knomi 2 on my Voron 2.4.
When running print the x any are showing some "reasonable" acceleration bar, the z bar is nailed to the top the most time, and sometimes s just drops 1-2 bars below max.
![2023-11-25_17-21-36](https://github.com/bigtreetech/KNOMI/assets/23736716/bffad618-1fb8-484f-82c7-a59eb88646cd)

Is this a mechanical issue with the part cooling fan, of the hot end fan?

**Comment by bigtreetech** [comment]
This is normal because there is gravitational acceleration (9.8 m/s²) in the z-axis direction

**Comment by lukicsl** [comment]
Is this a joke or a bug? If not a joke, why not subtract the earth's g-force or at least make it configurable if somebody prints on a space lab or the moon?

**Comment by jgefaell** [comment]
Me three. As it is, the Z-axis data is useless.

**Comment by bigtreetech** [comment]
> Is this a joke or a bug? If not a joke, why not subtract the earth's g-force or at least make it configurable if somebody prints on a space lab or on the moon?

Got it. will change the logic here and remove the z-axis gravity acceleration

**Comment by bigtreetech** [comment]
The latest version of firmware has subtracted 9.8 in the z-axis direction.
