### ISSUE TITLE
Change UI color on V2 Firmware with V1 Display

### ISSUE THREAD

**Issue by VoltexRB** [bigtreetech/KNOMI#43]
Since the V1 display isnt a touchscreen, how do I use the color changing wheel?
I have tried changing the default color in the firmware in the config.h file, but that seems to break the device upon flashing so that I can no longer successfully put my Moonraker IP in the webinterface without it replacing it in the text field with random errors.

**Comment by SrgntBallistic** [comment]
@VoltexRB did you figure this out?
