### ISSUE TITLE
Knomi 2 custom gifs?

### ISSUE THREAD

**Issue by NeighNeighNeigh** [bigtreetech/KNOMI#45]
In the Knomi 1 manual there are instructions to customise the animations – this is a great feature. Is this still possible in Knomi 2? there's no mention of it that I could find.

**Comment by bigtreetech** [comment]
same as knomi 1
https://bigtreetech.github.io/docs/KNOMI.html#customize-ui

**Comment by NeighNeighNeigh** [comment]
Excellent thank you 🙏
