### ISSUE TITLE
Kmoni V2.0 does not allow TCP Port specification for Klipper Host

### ISSUE THREAD

**Issue by jgefaell** [bigtreetech/KNOMI#48]
The IP address field only allows for 16 characters. This does not allow for a port specification which is necessary for multiple printer Klipper configurations as well as for the Creality K1. The device cannot be used for these printers. 

I, for instance, have three printers connected to two Klipper hosts, and a Creality K1 Max. I cannot use Knomi V2.0 with three of these printers. 

Note that Knomi V1.0 allowed the port specification, so this should be considered a regression. 

Thank you for your consideration. I'm keen to make use of Knomi V2.0!

**Comment by bigtreetech** [comment]
Got it.  Do it now.

**Comment by lech91** [comment]
> Got it. Do it now.

I dont get it, is it fixed? I installed the new firmware and wasnt able to add the port

**Comment by bigtreetech** [comment]
> > Got it. Do it now.
> 
> I dont get it, is it fixed? I installed the new firmware and wasnt able to add the port

Please try the the latest version of firmware again. Just uploaded the precompiled binaries now.

If you want to know the details of the changes, you can view the commit here
https://github.com/bigtreetech/KNOMI/commits/firmware/
