### ISSUE TITLE
Animations have low fps after uploading Firmware

### ISSUE THREAD

**Issue by oMTEo** [bigtreetech/KNOMI#6]
As the title says after I uploaded compiled code via VSCode to a Knomi the animated Voronlogo/Emotes have very bad low fps. Maybe there are some settings missing in the firmware.

**Comment by oMTEo** [comment]
It works now, Ive forgot to use this platform package -> https://github.com/z1996xm/arduino-esp32

**Comment by Surion79** [comment]
@oMTEo can you please close this issue since it is no longer an issue? Thanks :)

**Comment by oMTEo** [comment]
Done :)
