### ISSUE TITLE
Homing certain axis homes all

### ISSUE THREAD

**Issue by neriux912** [bigtreetech/KNOMI#7]
Homing only one axis, homes all of them. Not work either clicking in Webui or issuing command in console

**Comment by Surion79** [comment]
I hope the PR I created comes through. Then this is no longer an issue

**Comment by neriux912** [comment]
> I hope the PR I created comes through. Then this is no longer an issue

is there any clear instructions online, how to recompile firmware?

**Comment by SrgntBallistic** [comment]
> how to recompile firmware?

https://bigtreetech.github.io/docs/KNOMI.html#customize-ui

Outlined here. Setup VS Code with platformIO. Connect via USB-C -> verify/compile and upload
