### ISSUE TITLE
Mounting plate?

### ISSUE THREAD

**Issue by appleimperio** [bigtreetech/KNOMI#8]
Where is the sty for the mounting plate?

**Comment by neriux912** [comment]
> Where is the sty for the mounting plate?

https://github.com/neriux912/KNOMI/blob/master/Customized%20Printed%20Parts/Mounting%20Plate.stl

**Comment by appleimperio** [comment]
Is the same? why is not in the Bigtreetech GitHub?

**Comment by neriux912** [comment]
> Is the same? why is not in the Bigtreetech GitHub?

it's pulled out from step file

**Comment by appleimperio** [comment]
ok Thanks
